name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Étape 1 : Récupérer votre code
      - name: Get my code
        uses: actions/checkout@v4

      # Étape 2 : Configuration SSH complète
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          
          # Créer les clés
          echo "${{ secrets.BASTION_SSH_KEY }}" > ~/.ssh/bastion_key
          echo "${{ secrets.TARGET_SSH_KEY }}" > ~/.ssh/target_key
          chmod 600 ~/.ssh/bastion_key
          chmod 600 ~/.ssh/target_key
          
          # Configuration SSH
          cat > ~/.ssh/config << 'EOF'
          Host bastion
            HostName portier.polytech-lille.fr
            User rlavogie
            Port 2222
            IdentityFile ~/.ssh/bastion_key
            StrictHostKeyChecking no
            UserKnownHostsFile /dev/null
          
          Host target
            HostName jardin.plil.info
            User root
            IdentityFile ~/.ssh/target_key
            ProxyJump bastion
            StrictHostKeyChecking no
            UserKnownHostsFile /dev/null
          EOF

      # Étape 3 : Test de connexion
      - name: Test connections
        run: |
          echo "Testing bastion..."
          ssh bastion "echo 'Bastion OK'"
          
          echo "Testing target via bastion..."
          ssh target "echo 'Target OK'"

      # Étape 4 : Déploiement direct
      - name: Deploy files
        run: |
          # Déployer directement avec ProxyJump
          scp -r ./* target:/var/www/html/
          
          # Corriger les permissions
          ssh target "chown -R www-data:www-data /var/www/html && echo 'Deployment complete!'"
